package ru.myit.vlevpn.domain.model

data class ServerProfile(
    val id: ServerId,
    val name: String,
    val protocol: ProxyProtocol,
    val host: String,
    val port: Int,
    val credential: String,
    val password: String,
    val method: String,
    val transport: String,
    val security: String,
    val sni: String,
    val path: String,
    val flow: String = "",
    val fingerprint: String = "",
    val publicKey: String = "",
    val shortId: String = "",
    val spiderX: String = "",
    val networkMode: String = "",
    val headerHost: String = "",
    val subscriptionId: String = "",
    val subscriptionName: String = "",
    val subscriptionImportedAtMillis: Long = 0L,
    val subscriptionActivatedAtMillis: Long = 0L,
    val subscriptionPosition: Int = 0,
    val subscriptionUpdateIntervalHours: Int = 0,
    val subscriptionUploadBytes: Long = 0L,
    val subscriptionDownloadBytes: Long = 0L,
    val subscriptionTotalBytes: Long = 0L,
    val subscriptionExpireAtMillis: Long = 0L,
    val subscriptionSupportUrl: String = "",
    val subscriptionWebPageUrl: String = "",
    val subscriptionSourceUrl: String = "",
    val subscriptionAnnounce: String = "",
    val subscriptionAutoUpdateOnLaunchEnabled: Boolean = false,
    val subscriptionProviderId: String = "",
    val subscriptionProviderDomainHash: String = "",
    val protocolPayloadJson: String = "",
    val customJson: String,
    val createdAtMillis: Long,
    val updatedAtMillis: Long,
) {
    val isCustomJson: Boolean = protocol == ProxyProtocol.CUSTOM_JSON
    val isOlcRtc: Boolean = protocol == ProxyProtocol.OLCRTC
}
